//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace MedicApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caso
    {
        public int Id { get; set; }
        public int Paciente_Id { get; set; }

        public int Doctor_Id { get; set; }



        [DataType(DataType.Date)]
        public System.DateTime Fecha_entrada { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Fecha_salida { get; set; }
        



        public virtual Paciente Paciente { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
